---
deployment:
  tasks:
    - export DEPLOYPATH=/home/berandad/smartnews.berandadigital.net
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -rf * $DEPLOYPATH/
    - /bin/cp -f .env.example $DEPLOYPATH/.env.example 2>/dev/null || true
